In [1]:
import numpy as np

# Creating a Matrix using numpy

In [2]:
matrix_1 = np.array([[2,4],[5,4]])

matrix_1

array([[2, 4],
       [5, 4]])

In [3]:
matrix_1.shape

(2, 2)

In [4]:
matrix_2 = np.array([[34, 45, 65],[54,23,12], [45,56,42]])

matrix_2

array([[34, 45, 65],
       [54, 23, 12],
       [45, 56, 42]])

In [6]:
matrix_2.argsort(axis=1)

array([[0, 1, 2],
       [2, 1, 0],
       [2, 0, 1]], dtype=int64)

# Creating Matices With Random Values


In [7]:
random_matrix = np.random.rand(3,3)

random_matrix

array([[0.41700176, 0.49790975, 0.10543897],
       [0.95478094, 0.31759534, 0.73137174],
       [0.11179938, 0.76082519, 0.14400775]])

In [9]:
# Random Matrix with Integer Values
rand_mat = np.random.randint(10, size=(3,3))

rand_mat

array([[5, 1, 4],
       [6, 4, 4],
       [1, 0, 8]])

# Matrix With All Values 1

In [19]:
matrix = np.ones((3,3))

matrix

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
matrix.dtype

dtype('float64')

In [24]:
matrix = np.ones((3,3), dtype=int)

matrix

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

# Null Matrix

In [26]:
null_matrix = np.zeros((3,3))

null_matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# Identity Matrix

In [30]:
matrix = np.eye(6,6)

matrix

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

# Transpose Of A Matrix

In [41]:
matrix = np.random.randint(100,size=(3,3))

In [42]:
matrix

array([[62, 77, 57],
       [32, 64,  3],
       [70, 55, 51]])

In [45]:
transpose_matrix = matrix.T

transpose_matrix

array([[62, 32, 70],
       [77, 64, 55],
       [57,  3, 51]])

In [46]:
matrix = np.random.randint(10,size=(4,5))

In [47]:
matrix

array([[2, 9, 1, 0, 3],
       [5, 4, 0, 4, 4],
       [4, 3, 0, 1, 6],
       [1, 1, 1, 8, 4]])

In [48]:
matrix.T

array([[2, 5, 4, 1],
       [9, 4, 3, 1],
       [1, 0, 0, 1],
       [0, 4, 1, 8],
       [3, 4, 6, 4]])